apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    #qual é o endereço da API do lestencypt ???
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jorge@sti.ufpb.br
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx